---
USER_NAME:  user1
git_server: gitea.app.cluster.xyz
cluster_domain: app.cluster.xyz
model_git_url: https://github.com/nine-thousand-models/nine-thousand-models.git
alert_trigger: false
apply_feature_changes: false
linting: false
static_code_analysis: false
image_scan: false
image_signing: false
generate_sboms: false